htcondor/htcondor-ce

config/01-ce-auth-defaults.conf, config/01-ce-auth.conf, config/condor_mapfile, src/condor_ce_router_defaults
This provides two new pieces of functionality:
1) Allow the site-level HTCondor-CE collector to accept startd ads
from worker nodes; advertise the collector's address in the job
environment.  This is meant to work in conjunction with a new
gWMS feature in 3.2.9 / 3.2.10 (exact release unknown) which advertises
the pilot startd ad.  This will enable Miron's long-standing
request to make pilot ads visible to the CEs.
2) Implement a new attribute, minWalltime, which specifies a minimum
valid runtime for a job; if the pilot runs for less than this amount
of time, it is considered to be a problematic job and put on hold.
This will allow site admins more visibility into problem pilots and
worker nodes.
=> Updated functionality for Syracuse OSG site.

src/condor_ce_info_status
since plain putting the collector as a positional argument doesn't work, you must use --pool instead
=> Fix usage message to tell the user to use --pool

src/condor_ce_info_query.py
If --vo was unspecified, the script would add a constraint against the
VO 'None'.  This fixes it.
I also tried to make some tweaks in filterResourceAds to reduce
duplication, but after they failed, I added a comment with an
explanation of why the duplication is necessary.
=> Fix for SW-1782 (--vo broken if missing in condor_ce_info_status)

config/condor_mapfile
So the field separator appears to be ' ' in the CERTIFICATE_MAPFILE so I wrapped the entire regex in quotes. Tried it on my CE and it looks like it was able to parse it:
> 03/27/15 10:13:02 MapFile: Canonicalization File: method='gsi' principal='(/CN=[-.A-Za-z0-9/= ]+)' canonicalization='\1@unmapped.opensciencegrid.org'
=> Fix malformed pilot regex

src/condor-ce
JOB_ROUTER_ENTRIES is incorrect
=> Fail to start the HTCondor CE if the syntax of JOB_ROUTER_DEFAULTS or

CMakeLists.txt, config/01-ce-collector-requirements.conf
This expression keeps rogue sites from being able to send CE ads, or
xrootd startd/master ads for other sites.  This should get rid of the
need for a whitelist of sites that can send ads.
This is for SOFTWARE-1790 / SOFTWARE-1820.
=> Add COLLECTOR_REQUIREMENTS expression to ce-collector config

src/condor_ce_run
https://jira.opensciencegrid.org/browse/SOFTWARE-1910
Do not utilize the CE config when submitting a job with condor_ce_run
without the -r option (SOFTWARE-1910). When the CE config was used, a
grid universe job would be submitted to the HTCondor CE queue, which by
default puts grid universe jobs on hold.
=> Fix condor_ce_run without the '-r' option (SOFTWARE-1910)

src/condor_ce_router_defaults
Add default_remote_cerequirements.  This enables the administrator to
specify routes with the attribute default_remote_cerequirements, which
will then be appended to the remote_cerequirements.  Therefore, to add
a new type of resource (such as a gpu), the admin needs to:
1. Add to the default_remote_cerequirements in the router entry so
that the local submit file (.sh) can pick up the new requirement.  For
a GPU, it would be:
```
set_default_remote_cerequirements = "RequestGpus == 1"; \
```
2. Add to the [pbs|lsf|sge|…]_local_submit_attributes.sh an if
statement to capture and use this attribute.  Again, for a GPU and
Slurm:
```
if [ -n "$RequestGpus" ]; then
echo "#SBATCH --gres=gpu:$RequestGpus"
echo "module load cuda/6.0"
fi
```
=> Add default_remote_cerequirements

src/condor_ce_run
condor_ce_run without '-r' (SOFTWARE-1910)
=> Use default client auth methods (i.e., don't add GSI) when running

src/condor_ce_host_network_check
If we suspect sysadmins have a bad network setup, we should be able to run this script to diagnose this without having to go through HTCondor logs.
=> Add script to validate network settings.

src/condor_ce_host_network_check
This tries to replicate the logic of the "default address" HTCondor will use.
We want to verify the forward/backward mapping of this address matches the hostname on the certificate.  Otherwise, the child daemon may not authenticate the master.
=> Try to determine the address HTCondor would use.

config/01-ce-collector-defaults.conf
If a CE drops offline, cache their ads centrally for awhile.
=> Record absent ads in the collector.

src/condor_ce_router_defaults
CE by setting 'export DISABLE_GLIDEIN_ADS=True' in
/etc/sysconfig/condor-ce (https://ticket.grid.iu.edu/26666).
=> Add the ability for admins to disable glideins advertising back to the

src/condor_ce_router_defaults
Since eval_set_* happens after set_*, we need to switch how we set AccountingGroup and AccountingGroupOSG
=> Fix evaluation of UID and extattr tables (SOFTWARE-2067)

config/01-ce-auth-defaults.conf, config/01-ce-auth.conf
Due to a memory leak in lcmaps, we'd like to make fewer GSI authentication callouts.
=> Enable GSI map caching to decrease the number of GSI callouts

config/05-ce-view-defaults.conf
Cherrypy doesn't respect SIGTERM signals, so we must use the SHUTDOWN_FAST_TIMEOUT
to SIGKILL the ce-view after 10 seconds.
=> Use SHUTDOWN_FAST_TIMEOUT to kill the ce-view after 10 seconds.

config/htcondor-ce.spec, contrib/puppet/osg_ce_condor/files/config.d/01-ce-router.conf, src/condor_ce_router_defaults, tests/test_inside_docker.sh
A few spots with references to the RSL/classad libraries were missed. Build passed here: https://travis-ci.org/brianhlin/htcondor-ce/builds/111019051
v2.0.1 should be ok though even if we leave the JOB_ROUTER_DEFAULTS RSL functions in there because of all the null value handling.
=> Drop all RSL references (SOFTWARE-2205)

src/condor_ce_router_defaults, src/condor_ce_trace, src/htcondorce/tools.py
This patch allows HTCondor-CE to use lines out of `/etc/osg/extattr_table.txt` to be matched against the user's subject DN in addition to their VOMS attributes. Instead of [x509UserProxyFirstFQAN](http://research.cs.wisc.edu/htcondor/manual/v8.4/12_Appendix_A.html#100112), we use [x509UserProxyFQAN](http://research.cs.wisc.edu/htcondor/manual/v8.4/12_Appendix_A.html#100116), which includes the subject DN as well as the VOMS FQAN in a single attribute.
`condor_ce_trace` was also fixed to generate an `x509UserProxyFQAN` that mimics the format of the attribute created via `condor_submit`.
=> Accept subject DNs in extattr_table.txt (SOFTWARE-2243)

config/htcondor-ce.spec, tests/test_inside_docker.sh
Now that there's `condor-python` package available, we don't need to require the htcondor.so() directly and just let yum handle getting the proper architecture.
=> Make HTCondor-CE a noarch build

src/condor_ce_router_defaults
Tested this against:
- Empty `uid_table.txt`, contents in `extattr_table.txt`
- Contents in `uid_table.txt`, empty `extattr_table.txt`
- Contents in both `uid_table.txt` and `extattr_table.txt`
Time to start working on those unit tests...
=> Fix bug for incorrect number of parens (SOFTWARE-2243)

config/05-ce-view.conf
Adding the Schedd for dedicated ce-collectors and ce-view machines.
The Schedd is necessary for the Schedd cron which runs the metrics
updates.  Additionally, add example configuration which will turn
off all job submission abilities to this schedd.
SOFTWARE-2268
=> Adding Schedd to the CEView for the Schedd Cron

config/01-ce-auth-defaults.conf, config/01-ce-auth.conf
Fixes [SOFTWARE-2280](https://jira.opensciencegrid.org/browse/SOFTWARE-2280):
> The GridManager needs permissions to file transfers. Current fix is to add condor@child/$(FULL_HOSTNAME) to FRIENDLY_DAEMONS from 01-ce-auth.conf.
=> Add child as authorized daemon.

config/condor_mapfile
UNESP's CE daemons were having issues authenticating because the hostcert was not recognized in the `condor_mapfile`.
=> Add BR ANESP hostcert (https://ticket.opensciencegrid.org/29196)

src/condor_ce_router_defaults, tests/extattr_table.txt, tests/run_tests.py, tests/test_condor_ce_router_defaults.py, tests/test_inside_docker.sh, tests/uid_table.txt
I wrote some unit tests for `condor_ce_router_defaults` that test the `AccountingGroupOSG` generator functions. They've also been added to the Travis-CI tests.
=> Accounting Group unit tests

config/01-ce-router-defaults.conf.in, config/01-ce-router.conf.in
We've been seeing this more among sites. I don't think there's a way to differentiate between the job not matching any routes or the routes being full from the JobAd so this is better than nothing.
=> Adjust hold message for reaching MaxJobs or MaxIdleJobs

tests/test_inside_docker.sh
Even though the 3.2.29 yum man page says `yum clean all` performs all of the clean options, closer inspection of the client shows that it skips the `expire-cache` option. We perform the same two  commands in [osg-test](https://github.com/brianhlin/osg-test/blob/master/osgtest/library/yum.py#L16).
=> Add expire-cache cleaning since it's skipped with 'yum clean all'

config/htcondor-ce.spec, src/condor_ce_trace, tests/test_inside_docker.sh
Let's see if osg-test can run quickly enough to make sense for the CI build.
=> Enable osg-test run for travis-ci PRs.

tests/setup_tests.sh
Adding the `-xe` command for testing so that if any of the command exits with non-zero status, all of it will exit.
=> Adding -xe to bash command for testing

src/condor_ce_trace
We tell users in the [submitting jobs document](https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/SubmittingHTCondorCE) that they need to prepend some of their attributes with '+'. Before this change, `condor_ce_trace` would fail on such attributes.
=> Accept submit attribute format, '+AttributeName'

src/condor-ce
If /var/run or /var/lock happen to be on tmpfs filesystems, then the subdirectories
needed at runtime for htcondor-ce do not exist.  This commit adds code to the start()
function in /etc/rc.d/init.d/condor-ce to ensure the RUN and LOCK directories
are created and assigned the correct ownership.
Bug: https://ticket.grid.iu.edu/30906
=> Ensure lockdir and rundir exist with correct permissions on startup

config/condor_config
to use CERTIFICATE_MAPFILE in 8.5.6 (SOFTWARE-2412)
=> Force 'condor_ce_q -allusers' until QUEUE_SUPER_USER is fixed to be able

src/condor_ce_router_defaults
https://jira.opensciencegrid.org/browse/SOFTWARE-2440
> HTCondor doesn't have a `null` value but rather `undefined` when referring to non-existent ClassAd attributes. In our `JOB_ROUTER_DEFAULTS`, we make a lot of comparisons to `null` to check for attributes, which turns out to work because checking for `null` checks for the `null` attribute, which is generally `undefined`. We should update the `JOB_ROUTER_DEFAULTS` to refer to the correct value.
=> Change 'null' to 'undefined' in the JOB_ROUTER_DEFAULTS (SOFTWARE-2440)

CMakeLists.txt, config/htcondor-ce.spec
https://jira.opensciencegrid.org/browse/SOFTWARE-2444
Also a bonus commit that adds `%post`, `%preun`, and `%postun` sections that may relieve annoyances when updating the central collectors e.g. new config not taking effect because the service wasn't restarted.
=> Move tmpfiles config to /usr/lib/tmpfiles.d (SOFTWARE-2444)

config/01-ce-router-defaults.conf.in, config/01-ce-router.conf.in
https://jira.opensciencegrid.org/browse/SOFTWARE-2539
There are at least 3 reasons that the Job Router will ignore idle jobs
in the Schedd for 30 min+:
1. Job did not match any available job routes
2. All potential job routes are full (i.e. reached MaxJobs)
3. Routed jobs are failing and throttling occurs; job submission rates
drop and the job router does not pick up new jobs until the failure
rate drops below the configured threshold
Rather than including them in a very long hold message, it makes more
sense to elaborate the reasons in our documentation.
=> Fix hold msg for jobs not picked up by the JR (SOFTWARE-2539)

src/condor_ce_router_defaults
TotalSubmitProcs is used in 8.5.7 for the for job totals in the new
condor_q formatting. If a user queues multiple jobs in their submit
file (resulting in multiple ProcIDs), the job router creates unique
ClusterIDs in the target SchedD for each ProcID. Each of these routed
jobs retains the TotalSubmitProcs from the original jobs and condor_q
reports erroneously large job totals.
@IainSteers encountered this issue and it's still being investigated since the target SchedD, if it's 8.5.7+, should be squashing the routed job's `TotalSubmitProcs` attribute. That being said, this change is defensive in nature and jobs without `TotalSubmitProcs` defined are unaffected.
=> Remove TotalSubmitProcs attribute in routed jobs

src/condor_ce_info_status, src/htcondorce/info_query.py
Don't crash if entries are received from the collector with missing values for `CPUs` or `Memory`. Also handle if the attribute for `CPUs` is actually `Cpus`. This is for SOFTWARE-2185.
=> condor_ce_info_status: safely handle bad data

config/condor_mapfile
GOC ticket here: https://ticket.opensciencegrid.org/31952 
We should think about adding something to the documentation so that users can identify the host cert not being in the map file as an issue and how to add a regex to the condor_mapfile themselves.
=> Accept Russian Data Intensive Grid certs

CMakeLists.txt, config/htcondor-ce.spec, src/condor_ce_startup, src/verify_ce_config.py
We want to catch set_ATTR lines in JOB_ROUTER_ENTRIES for ATTR that
are eval_set_ATTR in JOB_ROUTER_DEFAULTS because they end up as
NOOPs. We were accidentally catching eval_set_ATTR statements in
JOB_ROUTER_ENTRIES, which we recommend against because they overwrite
their respective expressions in JOB_ROUTER_DEFAULTS but are
ultimately allowed.
=> Do not catch eval_set_ in JOB_ROUTER_ENTRIES (SOFTWARE-2581)

src/condor_ce_router_defaults
If a user requests CPU via condor's standard "request_cpu" submit
attribute, we should respect it. We check if the value is 1 because
newer versions of condor_submit automatically set "RequestCpus =
1". The one limitation of this method is that users cannot submit jobs
with "request_cpus = 1" and have that respected if the admin has set a
default_xcount.
https://jira.opensciencegrid.org/browse/SOFTWARE-2598
=> Respect RequestCpus of incoming jobs (SOFTWARE-2598)

src/condor_ce_router_defaults
eval_set_<attr> expressions don't like it if they have <attr> within them. Tested the fix and `RequestCpus` is properly set on the routed job.
=> Fix assignment of RequestCpus (SOFTWARE-2598)

src/condor_ce_env_bootstrap
Instead, we'll depend on the default value that is compiled in to LCMAPS.  SOFTWARE-2633
=> Do not explicitly disable VOMS credential check.

src/condor_ce_router_defaults
When WholeNodeWanted=true, request the following resources for the job:
- TotalCpus of the worker
- 95% of TotalMemory
Implements the method from "Getting To Multicore: Resizing jobs in CMS" by @bbockelm. HTCondor Week 2016.
https://research.cs.wisc.edu/htcondor/HTCondorWeek2016/presentations/ThuBockelman_ResizableJobs.pdf
=> Add WholeNodeWanted ClassAd expression to request whole-node jobs

config/htcondor-ce.spec
We no longer build classad functions
=> Drop boost/cmake build requires

src/condor_ce_router_defaults
OSG factory operations has an existing convention of "Want{Item}", e.g. WantSingularity.
For whole node support added in #142, change flag from WholeNodeWanted to WantWholeNode to match existing factory naming convention.
=> Use WantWholeNode to match existing factory naming convention

config/htcondor-ce.spec
boost-devel and cmake removed in 3eb0476 but we still need the
latter. Passed our CI tests because we install cmake directly.
=> Bring back cmake

src/condor_ce_router_defaults
When a whole node job is matched, we need to save the number of cpus
so that accounting systems can pick up how many cpus where actually 
used by a job.
=> Save the number of CPUs allocated at last match

src/condor_ce_router_defaults
Hi @djw8605, @brianhlin, and @bbockelm,
Troubleshooting failed jobs, I found that the memory requirements were not passing through BLAHP to the local scheduler (pbs_submit.sh -> SLURM).
When passing a job to a GAHP server, gridmanager [copies](https://github.com/htcondor/htcondor/blob/f7ac6cce/src/condor_gridmanager/infnbatchjob.cpp#L1381-L1396) a limited list of attributes, which includes RequestMemory.
With the whole node changes (#142), RequestMemory is now an expression that includes OriginalMemory. But, OriginalMemory is not passed along by gridmanager, so BLAHP cannot evaluate RequestMemory.
Please consider this PR as an ugly proof-of-concept. It appears to get RequestMemory passed to the local scheduler, but I'd appreciate your help on making it cleaner.
Regards,
John
=> Pass OriginalMemory variable through GAHP

config/01-ce-router-defaults.conf.in, config/01-ce-router.conf.in
Address issue reported in SOFTWARE-2803:
* The proxy in the spool directory on the CE is not necessarily the one used to communicate between the factory and the CE.  An expired proxy can be subsequently updated.
* The glideinWMS pilot only needs to do a GSI auth to establish an initial connection to the collector - afterward, it uses the established HTCondor security session between startd and collector.
=> Do not hold running jobs with expired proxy (SOFTWARE-2803)

config/htcondor-ce.spec, src/audit_payloads.py
This fixes a bug I found that was losing a small percentage of stop messages.
=> fix when a startjob first stops the last job in a master

src/audit_payloads.py
I found when testing this through condor_ce_run that the setting for $CONDORCE_COLLECTOR_HOST includes the port :9619, so I remove the port in the comments about how to use the audit payload logging function.
=> fix comment -- remove explicit port for CE

config/05-ce-view-defaults.conf, config/05-ce-view.conf
https://jira.opensciencegrid.org/browse/SOFTWARE-2820
Users were seeing their CE Views getting killed after 24 hours (the security session default lifetime) 
Since the CE View starts up as root, it has access to the hostkey so it could send keepalives until the initial security session died. After it tries to get a new security session, it's running as the 'condor' user so it can't access the hostkey, can't send keepalives, and the master kills it. 
Prefer FS auth over GSI for the master and only auth the CE View via FS. We don't fix this for the central collector because the OSG cc uses IP load balancing and certs with SANs, which don't work in HTCondor for auth (https://htcondor-wiki.cs.wisc.edu/index.cgi/tktview?tn=6135,86).
=> CEView daemon doesn't have permission to send keepalive to CE Master

config/htcondor-ce.spec, src/condor_ce_trace
http://condor-wiki.cs.wisc.edu/index.cgi/tktview?tn=6502
This caused `condor_ce_trace` to fail with 8.7.5
=> Handle missing 'MyTpe' attr in 8.7.5

rpm/htcondor-ce.spec
The requirement for /usr/bin/voms-proxy-info can be satisfied by
either voms-clients-cpp or voms-clients-java, the latter of which
is now problematic for osg-3.3.  So, we'll just be explicit now
about which package to bring in.
=> require voms-clients-cpp explicitly (SOFTWARE-3201)

rpm/htcondor-ce.spec
CC-IN2P3 uses BDII and grabs HTCondor-CE from the condor repos
=> Build the BDII sub-package for everything but the OSG

contrib/bdii/htcondor-ce-provider
This is not required as it is handled by strip()
=> Remove regex from replace

CMakeLists.txt, rpm/htcondor-ce.spec, src/condor_ce_startup
This solution is currently incomplete as the `chown` via CMake doesn't work because of a non-existent condor user. I think this is better handled downstream via rpm/debian packaging. Do we still want to do the ownership verification via `condor_ce_startup`?
https://jira.opensciencegrid.org/browse/SOFTWARE-2806
=> Create required dirs on install (SOFTWARE-2806)

config/01-common-auth-defaults.conf, config/condor_config
The new condor_q behavior requires an authZ check and that can cause
failures when running condor_ce_q. We don't care who can query the CE
schedd so this isn't a security issue.
=> Revert the default condor_q behavior to query all users' jobs

src/condor_ce_view
See the ticket and first commit for details. I chose `WARNING` for the first message because a CE View could be fully functional without sending heartbeats, it just wouldn't be under the purview of the CE master. I could see it being reclassified as an `ERROR` that shows up for `htcondor.LogLevel.FullDebug`, though.
=> Only send keepalives as the 'condor' user; catch exceptions (SOFTWARE-3486)

src/htcondorce/web_utils.py
This failed for sites which did not set memory in the
resource catalog.
=> Adding default memory to queue information

config/05-ce-view-defaults.conf
This reverts commit 765f8a8cc4736f12e5c58bab3e2d2411a4812665.
@matyasselmeci whelp, @timtheisen pointed out that this actually hasn't been addressed in HTCondor yet so I'm reverting it
=> Revert "Update the central collector via TCP (SOFTWARE-3668)"

src/condor_ce_router_defaults
We will tell users to "set_default_CERequirements" and eval_set*
happens after set_*:
https://opensciencegrid.org/docs/compute-element/job-router-recipes/#editing-attributes
=> Ensure that CERequirements has access to default_CERequirements

rpm/htcondor-ce.spec
Strangely, the official systemd_post macro doesn't include this
=> Add 'systemctl daemon-reload' back to avoid warnings

config/condor_mapfile, docs/installation/htcondor-ce.md
Mapped HTCondor principles without an '@' suffix automatically have
'@users.htcondor.org' appended since it's the default
UID_DOMAIN. Exposing this to users has lead to confusion where they
replace 'htcondor.org' with their own domain, resulting in failure to
submit jobs.
=> Remove unnecessary documentation references to 'users.htcondor.org'

config/01-common-auth-defaults.conf, src/condor_ce_client_env_bootstrap
This partially reverts commit 90cc27102aa1a37e3c7e1dfe92297a975bc158a4.
We had to re-enable optional encryption/integrity because of an issue
where HTCondor currently returns the IP instead of the alias:
53527005740d9c4434dabef39a27de1fd1b35ba4
=> Do not require authN for queue reads (SOFTWARE-3860)

CMakeLists.txt, rpm/htcondor-ce.spec, src/condor_ce_client_env_bootstrap, src/condor_ce_config_val, src/condor_ce_history, src/condor_ce_hold, src/condor_ce_job_router_info, src/condor_ce_off, src/condor_ce_on, src/condor_ce_ping, src/condor_ce_q, src/condor_ce_qedit, src/condor_ce_reconfig, src/condor_ce_release, src/condor_ce_reschedule, src/condor_ce_restart, src/condor_ce_rm, src/condor_ce_router_q, src/condor_ce_status, src/condor_ce_store_cred, src/condor_ce_submit, src/condor_ce_version
I thought about setting `TOOL.SEC_CLIENT_AUTHENTICATION_METHODS = SCITOKENS,GSI,PASSWORD` but we don't really even need to do that. All the `condor_ce_*` tools for which we have wrappers are really only useful when run locally on the CE, so `FS` should be the preferred auth method.
The only reason I could see someone wanting `SCITOKENS` or `GSI` would be to test their `condor_mapfile` mappings and they could just as easily do that 1) remotely or 2) by setting `_condor_SEC_CLIENT_AUTHENTICATION_METHODS=SCITOKENS,GSI`.
=> No reason to try non-FS methods first for client tools

contrib/apelscripts/condor_batch.sh, contrib/apelscripts/condor_blah.sh
The former scripts created badly formed records (when RemoteWallClockTime is undefined) and superfluous records (when RemoteWallClockTime is defined but is zero.) This did not affect the function of the system as a whole, since aggregate accounting figures were not corrupted. But the logs contain ugly messages, due to parsing errors and/or silly zero length jobs got sent to the portal. Both classes of problem are eliminated by this patch, which checks for undefined  RemoteWallClockTime and whether RemoteWallClockTime is zero. Such pointless records are omitted. This has been tested to show that the new versions are functionally identical to the old ones in the system as a whole, but do not cause the problems described. To do this test, the old and new  versions of blah and batch data …
=> Check RemoteWallClockTime is defined, to stop selecting irrelevant data

docs/index.md, mkdocs.yml, overwrite_theme/main.html
This PR overwrites the "material" theme used for the documentation to add a note to mention the version of the htcondor-ce for which the documentation was written.
=> Differentiate between HTCondor-CE 3 and 4 upstream documentation (software-3895)

docs/batch-system-integration.md
Cherry-picked from #306, slightly modified to prefer 8.9.x versions of HTCondor
=>  Add options for specifying job route order in new versions of HTCondor

contrib/bdii/htcondor-ce-provider
While setting up the new HTCondorCE at GRIF I had to modify this gip provider script provided by htcondor-ce-bdii-3.3.0-1.el7.noarch (which seems to be the master of this repo). Ive made just changes needed to make the bdii publication of the CE pass the glue-validator
>> glue-validator -k -v3 -H localhost -p 2170 -b o=glue 
OK - errors 0, warnings 0, info 0 | errors=0;warnings=0;info=0
I've also made some minor code formatting to have a 9.5/10 pylint rating (10/10 would require some major reorganization of the code). But, if you wish I can re-do this PR without the formatting and with 
only the minimal changes needed to pass glue2 validation.
As requested this PR was closed and reopened with split commits for the pylint and glue-validator parts
Regards,
Andrea SARITRANA (GRIF, IN2P3-LLR)
=> Glue validate

config/01-ce-auth-defaults.conf, config/condor_mapfile, config/condor_mapfile.osg
When GSS_ASSIST_GRIDMAP fails, it results in the authenticated
identity of "gsi@unmapped". Additionally, the failed mappings do not
fall through to other GSI lines in the mapfile so the second GSI
mapfile lines were unnecessary here.
=> Add gsi@unmapped to UNMAPPED_USERS (SOTWARE-4039)

src/verify_ce_config.py, tests/test_verify_ce_config.py
Check out c39c30d45b90fed8878ddff3235a9db3bfc1def2 for the bulk of the changes since the commit adding unit tests makes a big bulk indentation change.
This change is for `stable` and I'll cherry-pick the changes to `master` once they're approved. Closes #233
=> Identify misconfigured routes and fix bad ClassAd detection (SOFTWARE-3896, SOFTWARE-4052)

CMakeLists.txt, rpm/htcondor-ce.spec
In my rush to tag a version to get a DOI, I forgot to bump the packaging. I _think_ the [deploy](https://github.com/htcondor/htcondor-ce/blob/master/tests/sftp_upload.sh#L64-L67) will handle this fine but it's early so I could use a second pair of eyes.
=> Bump packaging

src/htcondorce/web_utils.py
The classad that Collector.locate() returns only contains "Name" and other minimal information to contact that daemon, not any of the other attributes we use elsewhere.
Once we have the Name, query the collector again to get the full schedd ad.
=> Return full ads in get_schedd_ads() even when only querying the local pool

CMakeLists.txt, contrib/apelscripts/50-ce-apel-defaults.conf, contrib/apelscripts/condor-ce-apel.service, contrib/apelscripts/condor-ce-apel.timer, rpm/htcondor-ce.spec
From #323, the APEL SchedD cron has not worked out due to various APEL directory permission issues. Replace it with a systemd service and timer.
=> Add APEL systemd service and timer

CMakeLists.txt, contrib/apelscripts/50-ce-apel-defaults.conf, contrib/apelscripts/condor-ce-apel, contrib/apelscripts/condor-ce-apel.cron, contrib/apelscripts/condor-ce-apel.service, contrib/apelscripts/condor-ce-apel.timer, rpm/htcondor-ce.spec
Fixes #233. Includes systemd changes cherry-picked from #330 and init/cron for EL6 support
=> Revert APEL cron (stable)

templates/index.html
index.html gets validated as if it were XHTML, so it should have the appropriate doctype
Closes #329
=> Fix wrong doctype

contrib/bdii/htcondor-ce-provider
(RT#100853)
`classad.ClassAd` only takes strings as input :(
=> Fix a stacktrace that occurs when HTCONDORCE_SPEC isn't defined

docs/installation/htcondor-ce.md, docs/overview.md, docs/troubleshooting/troubleshooting.md
This PR also includes
- Refer to all incoming jobs as pilots to hammer home the fact that the CE is designed exclusively for pilots
- Updates to supported auth methods
=> Update the overview to use terminology from the TCS paper

config/01-ce-router-defaults.conf.in, config/01-ce-router.conf.in, rpm/htcondor-ce.spec
Without excluding removed jobs, this hold expression can result in a
race condition where jobs are removed and immediately put back on hold
so that they remain in the queue and oscillate between these two states
=> Do not put removed jobs on hold

docs/troubleshooting/troubleshooting.md
Ideally I'd like to reorganize that doc and dump it under the "Central
Grid Operations" section but this will have to do for now.
=> Temporarily fixup link to OSG CE submission doc

docs/troubleshooting/troubleshooting.md
Ideally I'd like to reorganize that doc and dump it under the "Central
Grid Operations" section but this will have to do for now.
=> Temporarily fixup link to OSG CE submission doc (stable)

contrib/apelscripts/50-ce-apel-defaults.conf
Fixes the default APEL setting for the BATCH_HOST. This previously pointed to the CE host instead of the LRMS host.
This change relies on ``JOB_ROUTER_SCHEDD2_POOL`` pointing at the LRMS collector, which seems to be always valid when the LRMS is HTCondor.
=> Adjust APEL defaults of APEL_BATCH_HOST to lrms

rpm/htcondor-ce.spec
- Config file comments note `This file will NOT be overwritten on upgrade.`
- Config file shouldn't need to be executable
PR opened as draft as I haven't tested/rebuilt the package with the spec changes.
=> Spec fixes for /etc/httpd/conf.d/htcondorce_registry.conf

config/01-pilot-env-defaults.conf, config/01-pilot-env.conf, src/condor_ce_router_defaults
Addresses #374
Tested on a fermicloud VM and the `Environment` of the routed job included or excluded `HOME` when I set `USE_CE_HOME_DIR` to `True` or `False`, respectively
=> Allow users to unset the default home env var in the routed job

contrib/apelscripts/50-ce-apel-defaults.conf
This reverts commit 465221a84843c5d8ec4957c1f2dcee251e7cc643 from #371 
APEL_BATCH_HOST is used to construct the unique APEL batch record,
combining the local condor batch ID and the relevant host. Since job
IDs are unique to their submit hosts, this should be tied to the CE
host instead of the local central manager.
=> Revert "Adjust APEL defaults of APEL_BATCH_HOST to lrms"

src/condor_ce_jobmetrics
Refactor this function a bit in prep for other SOFTWARE-4183 work.
The most scary looking part was the using of `.values()` for the job_key, which i don't think is actually guaranteed to be sorted.  The rest is mainly intended to make this function easier to work with.
=> Tenderize process_one_schedd (SOFTWARE-4183)

rpm/htcondor-ce.spec
Basically the same as #384 except we don't care about Python 3 support for stable
=> Drop htcondor-ce requirement from htcondor-ce-bdii (stable)

config/01-ce-router-defaults.conf.in
This doesn't quite match the logic of https://github.com/htcondor/htcondor-ce/blob/master/src/condor_ce_router_defaults#L104-L109 since admins can set `default_maxWalltime` per route but it's a start for @maxfischer2781. Ultimately I think all the max walltime logic should be executed by the `SYSTEM_PERIODIC_REMOVE` in the CE layer but that depends on whether or not `JobCurrentStartExecutingDate` in the CE job is reasonable enough to use in both the HTCondor and non-HTCondor batch system cases.
Historically we've told pilot factories to submit jobs with [+maxWalltime](https://htcondor-ce.readthedocs.io/en/latest/remote-job-submission/#submit-file-commands) to cap the runtime (in minutes) of pilot jobs. Admins could also set `default_maxWallTime` per job route. However this is currently …
=> Remove jobs that exceed their requested max walltimes (HTCONDOR-80)

README.md, config/01-common-collector-defaults.conf, tests/Dockerfile.dev
Submitting this PR before I start performing major surgery on the CE View bits.
The fixup is required for HTCondor-CE to be able to run `audit_payloads` as a collector plugin.
=> Add development Dockerfile; minor Python 3 fixup

config/05-ce-view-defaults.conf
My test container's much happier now:
```
PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                                                              
1 root      20   0   11708   2448   2272 S   0.0  0.0   0:00.00 runme.sh                                                                                                             
7 root      20   0   11844   2884   2456 S   0.0  0.0   0:00.04 bash                                                                                                                 
18 condor    20   0   72036  12060  10004 S   0.0  0.1   0:00.77 condor_master                                                                                                        
106 root      20   0 …
```
=> Remove circular definition that caused condor_gangliad to thrash (HTCONDOR-161)

tests/install_rpms.sh, tests/test_inside_docker.sh
Running OSG tests against 8.9 fixes the collector stacktrace since 8.9 provides better Python 3 support for the collector plugins.
Note that OSG CE View tests are still failing but I'll tackle that in a separate PR
=> Fixup collector stacktrace; add a UW build check for the CE collector

config/01-pilot-env-defaults.conf, config/01-pilot-env.conf
This flips the switch here: https://github.com/htcondor/htcondor-ce/blob/V5-branch/src/condor_ce_router_defaults#L28-L30
=> Do not set HOME in the default job environment (HTCONDOR-176)

contrib/apelscripts/condor_batch.sh, contrib/apelscripts/condor_blah.sh
Instead of making up a custom LRMS job identifier, use the Condor-defined GlobalJobId.
This doesn't introduce arbitrary convention on the JobId format.
It also allows using the field directly in condor_history constraints.
=> Use GlobalJobId as unique job identifier

config/01-ce-router-defaults.conf.in, src/condor_ce_router_defaults
Instead of setting Walltime as a CERequirements attribute in the routed
job, set BatchRuntime (now supported by HTCondor and the blahp).
Also, recognize and use BatchRuntime in the source job ad.
=> Use job attribute BatchRuntime to set max wallclock time. HTCONDOR-80

config/01-ce-router-defaults.conf.in, src/condor_ce_version
Currently, it only prints the HTCondor version, which is helpful but not quite complete.
=> Add HTCondor-CE version information to condor_ce_version

config/01-ce-router-defaults.conf.in
It appears that JobCurrentStartExecutingDate does not get set in the
job ad so the expression nearly evaluates to True unless the admin
sets their max walltime to 50-some years
=> Fixup walltime removal expression (HTCONDOR-350)

config/01-ce-router-defaults.conf.in, src/condor_ce_version
Fixes the following issue:
```
03/17/21 13:52:03 (D_ALWAYS) CONFIGURATION PROBLEM: Failed to insert ClassAd attribute HTCondorCEVersion = 5.0.0.  The most common reason for this is that you forgot to quote a string value in the list of attributes being added to the SCHEDD ad.
```
=> SchedD attrs must be enclosed by double-quoted strings

config/01-ce-router-defaults.conf.in
Otherwise the expression evaluates to an int, which
SYSTEM_PERIODIC_REMOVE evaluates to True:
```
$ condor_ce_history -match 1 -format '%v\n' 'EnteredCurrentStatus - JobCurrentStartDate > maxWalltime is undefined ? 4320*60 : maxWalltime*60'
259200
$ condor_ce_history -match 1 -format '%v\n' '(EnteredCurrentStatus - JobCurrentStartDate) > (maxWalltime is undefined ? 4320*60 : maxWalltime*60)'
false
```
=> Ensure that we have the expected order of operations (HTCONDOR-350)

config/01-ce-router-defaults.conf.in
$() Expansions my not have internal spaces
evals happening at the wrong time for CERequirements and OnExitHold
=> fix syntax issues with new job router transforms for HTCONDOR-243

config/01-ce-router-defaults.conf.in
Two transforms that an Admin can add to the pre (or post) route transform list. One for setting AccountingGroup from UID and the other from x509
=> HTCONDOR-187 Add CE transforms to set accounting group from a UserMap

config/htcondorce_registry.conf, docs/releases.md, rpm/htcondor-ce.spec, src/htcondorce/registry.py
First pass at updating the registry to python3, removing Genshi and replacing it with Jinja2. This work is based on BrianL's previous work doing the same with the CE view scripts. Likely some things missing here.
=> Update HTCondor-CE registry to Python 3 (HTCONDOR-307)

CMakeLists.txt, rpm/htcondor-ce.spec
We can do the latter since we will only ship 5.x along with 9.0.x in the CHTC and OSG 3.5 upcoming/3.6 Yum repos
=> Update packaging for 5.1.0; drop (noreplace) for condor_mapfile

src/verify_ce_config.py
Split the value of JOB_ROUTER_ROUTE_NAMES on space/comma instead of
splitting into individual characters.
=> Fix check of job route names in CE configuration. HTCONDOR-406

config/02-ce-bosco-defaults.conf, config/02-ce-bosco.conf, config/02-ce-condor-defaults.conf, config/02-ce-condor.conf, config/02-ce-lsf-defaults.conf, config/02-ce-lsf.conf, config/02-ce-pbs-defaults.conf, config/02-ce-pbs.conf, config/02-ce-sge-defaults.conf, config/02-ce-sge.conf, config/02-ce-slurm-defaults.conf, config/02-ce-slurm.conf, docs/v5/releases.md, mkdocs.yml
A 'JOB_ROUTER_ROUTE_' will override a route in JOB_ROUTER_ENTRIES if
they have the same name, even if
'USE_JOB_ROUTER_DEPRECATED_ROUTER_ENTRIES = True' and the
'JOB_ROUTER_ROUTE_' is uses the transform syntax.
To avoid unexpectedly overrriding an existing CE's route (many of them
probably just stick with the default names we give), use a different
name in the transform syntax.
Also add some upgrade notes about the new transform syntax, including a
warning about transform routes that we provide by default. More detailed
docs about the transform syntax to come in another commit.
=> Fix default transform routes (HTCONDOR-243)

src/verify_ce_config.py
Now that we support job transforms, it's feasible that an admin won't
have JOB_ROUTER_ENTRIES or JOB_ROUTER_DEFAULTS defined (the latter
being more difficult since we generate them automatically). For now,
just downgrade this to a warning.
Doc URL doesn't exist yet, I've got a separate branch for it. See https://brianhlin.github.io/htcondor-ce/v5/configuration/writing-job-routes/#setting-job-environments for what I plan for it to look like
=> Downgrade CE config verify errors

src/condor_ce_view
Just `::1` was confusing gunicorn so it couldn't find the port and we listen on all addresses in IPv4 so we should do the same for IPv6
=> Fix IPv6 format

config/01-ce-router-defaults.conf.in, config/02-ce-condor-defaults.conf, config/02-ce-condor.conf, src/condor_ce_router_defaults
I haven't simplified the environment transform since the `{advertise_pilots}` string is shared between the transform and the `JOB_ROUTER_DEFAULTS`. I don't hardcode the string based on the various `DISABLE_PILOT_ADS` settings because I'd like users to be able to change that without having to restart the CE to see its effect.
=> Various router transform fixups (HTCONDOR-243)

config/01-common-collector-defaults.conf
Fixes this issue here (https://github.com/htcondor/htcondor-ce/runs/2273421329?check_suite_focus=true#step:12:200)
```
04/05/21 22:17:30 (D_ALWAYS) Failed to load plugin: /usr/libexec/condor/libcollector_python3_plugin.so reason: /usr/libexec/condor/libcollector_python3_plugin.so: cannot open shared object file: No such file or directory
```
Name grabbed from the EL7 base container:
```
$ podman run --rm -it htcondor/base:el7 /bin/sh -c "ls -l /usr/libexec/condor/libcollector*.so"
-rwxr-xr-x. 1 root root 44640 Mar 30 04:45 /usr/libexec/condor/libcollector_python_plugin.cpython-36m-x86_64-linux-gnu.so
-rwxr-xr-x. 1 root root 44608 Mar 30 04:45 /usr/libexec/condor/libcollector_python_plugin.so
```
=> Fix collector plugin path for HTCondor 8.9.11+ (HTCONDOR-400)

src/condor_ce_view
It seems like "daemon core" daemons are expected to handle setting their own signal mask(s) on start-up.
=> (HTCONDOR-420)  Unblock all signals at condor_ce_view start-up.

docs/v5/configuration/htcondor-routes.md, docs/v5/configuration/non-htcondor-routes.md, docs/v5/configuration/writing-job-routes.md
- Noticed a bug in our env setting via routes
- Make sure we're consistently using equals signs for `SET`, `EVALSET`, `EVALMACRO`, and job route variables
- Should we also move from `TargetUniverse` to `UNIVERSE`?
=> Use consistent equals signs (HTCONDOR-418)

contrib/apelscripts/condor_batch_blah.sh, rpm/htcondor-ce.spec
This PR adds defaults for APEL to ensure accounting does not skip jobs for a fresh installation.
* If a job's host did not define the ``APEL_SCALING_ATTR``, it is quarantined instead of reporting ``undefined`` (see https://github.com/apel/apel/issues/210)
* The default ``PER_JOB_HISTORY_DIR`` is created for user ``condor:condor`` (see #419)
The first change could alternatively set a default (as in an earlier commit). Since this may hide veritable configuration errors, excluding broken jobs and allowing manual recovery seemed preferable.
=> Safe defaults for APEL

docs/v5/configuration/authentication.md
@zmiller I didn't address your point about `/etc/grid-security/certificates/` because it's touched on in this sentence:
> But traditionally, CEs and their clients have authenticated with each other using specialized grid certificates (e.g.
certificates issued by [IGTF CAs](https://dl.igtf.net/distribution/igtf/current/accredited/accredited.in)) located in `/etc/grid-security/`.
=> Address auth doc  review comments (HTCONDOR-419)

docs/index.md, docs/v3/batch-system-integration.md, docs/v3/installation/htcondor-ce.md, docs/v3/job-submission.md, docs/v4/batch-system-integration.md, docs/v4/installation/central-collector.md, docs/v4/installation/htcondor-ce.md, docs/v4/releases.md, docs/v4/remote-job-submission.md, docs/v4/troubleshooting/remote-troubleshooting.md, docs/v5/configuration/htcondor-routes.md, docs/v5/configuration/job-router-overview.md, docs/v5/configuration/writing-job-routes.md, docs/v5/installation/central-collector.md, docs/v5/installation/htcondor-ce.md, docs/v5/releases.md, docs/v5/remote-job-submission.md, docs/v5/troubleshooting/remote-troubleshooting.md
Changed the doc links in v3, v4, and v5 to refer to HTCondor Manuals 8.8, 8.9.11, and 9.0 respectively.
=> Fixed Various Manual Links (HTCondor-421)

docs/v5/configuration/authentication.md, docs/v5/releases.md
The default `AUTH_SSL_*` config knobs lead to confusing token
authentication failures for folks that are used to grid cert/CA
locations
=> Add upgrade section about SSL cert locations

mkdocs.yml
When enabling other plugins, the search bar has to be explicitly enabled. Same as https://github.com/opensciencegrid/docs/pull/869
=> Re-enable search bar

config/01-ce-router-defaults.conf
Fix bugs and make more consistent with old syntax default route, in particular
RequestCpus from incoming job is ignored and overwritten unless > 1
RequestMemory from incoming job is ignored and overwritten
We do this because CE Admins are reporting that incoming values for RequestCpus
and RequestMemory are often the minimal defaults set by condor_submit rather than
=> HTCONDOR-662 Fix post-route for CPUs and Memory

config/01-ce-router-defaults.conf
(HTCONDOR-718)
This change makes the default MaxJobs and MaxIdleJobs the same across transform and JRD/JRE syntaxes
=> Ensure default MaxJobs/MaxIdleJobs are the same for all JR syntaxes

tests/containers/entrypoint/renew-demo-token.py
BEARER_TOKEN is the contents of the token; BEARER_TOKEN_FILE is the path to the token file
=> Get the right env var for the token path

contrib/apelscripts/condor_batch_blah.sh
This PR changes the printf format specifier used to create APEL records. Previously it was signed int (32 bit) which would wrap around for excessive ``ImageSize_RAW = 79495059964``.
I have changed *all* fields to signed long long int. This is not strictly needed but has no negative impact and seemed more consistent.
Closes #518. FYI @thdesy
=> Format APEL records with maximum integer length (HTCONDOR-826)

docs/v5/troubleshooting/common-issues.md
We ship the default config (https://github.com/htcondor/htcondor-ce/blob/01a3cdae31eb5b066a64dbc5b3d1503c2ce52a25/config/01-ce-auth-defaults.conf#L77-L78)
```
SCHEDD_AUDIT_LOG = $(LOG)/AuditLog
SCHEDD_DEBUG = D_AUDIT
```
=> SchedD D_AUDIT messages show up in AuditLogs

config/01-ce-router-defaults.conf
Without this, users always get:
CERequirements = "default_CERequirements,CondorCE"
=> Fix reference to default_CERequirements job attr (HTCONDOR-964)

.github/workflows/build_and_test_rpms.yml, rpm/htcondor-ce.spec
I fixed up the build failures. These are purely mechanical changes.
- osg-3.5-upcoming is no longer supported, dropped from build
- package additional .pyc files for apel script (on EL7)
=> HTCONDOR-1206: Fix failed builds

src/condor_ce_startup
These existance/permission checks assume the admin hasn't altered the default locations, and least SPOOL is likely to ben relocated. The condor_master will create these directories if necessary, in the locations given in the configuration files.
Leaving the checks for LOG and LOCK, since the master needs to write to its log file before creating these directories and the user subdirectories are not created by the master.
=> HTCONDOR-1522 Remove some hard-coded directory permission checks

README.md
As discussed in the team meeting: This adds an **Issues** section to the README.md to have links to various mailings lists in order to turn off the github issues section
=> HTCONDOR-1641: Update CE repo readme with mailing lists

config/01-ce-auth.conf, config/01-common-auth-defaults.conf
Now, the base configuration works out-of-the-box with either the standard or grid certificate file locations.
Also, disable and ignore the collector's autogenerated CA and host cert.
=> HTCONDOR-1651 Overhaul SSL certificate configuration

src/verify_ce_config.py
When routing into a local HTCondor pool, verify that the job router will find the local schedd's SPOOL directory.
=> HTCONDOR-1663 spool-config-check

src/condor_ce_trace
Useful for admins to test CE -> local batch submission without having to worry about the SciToken credentials
=> Add the ability to attempt submission without a credential (HTCONDOR-1787)

config/01-ce-router-defaults.conf, src/condor_ce_router_defaults
Condor-C jobs won't have this check added automatically and startds that don't have GPU detection won't include a check. If we don't add a check here, then jobs with RequestGPUs set can end up running on machines with no GPUs when routed to a local HTCondor pool.
We only set Requirements if it's currently the literal value 'true'. We expect newer clients to start setting all of the automatic requirements clauses for Condor-C jobs, and we don't want to ignore those.
=> HTCONDOR-2193 gpu-reqs

config/01-ce-router-defaults.conf
When default_CERequirements isn't set in the job ad, '$F(MY.default_CERequirements)' expands to 'MY.default_CERequirements' instead of an empty string.
=> HTCONDOR-2276 cereqs-default

src/condor_ce_router_defaults
The macros CONDORCE_PILOT_JOB_ENV and default_pilot_job_env should already include quotes, so adding quotes results in a ClassAd syntax error. default_pilot_job_env may be undefined, so set a default of "".
=> HTCONDOR-2322 job-env-transform

config/01-ce-router-defaults.conf
The old expression would evaluate to Undefined for grid universe jobs, leading to no memory request being passed to the blahp.
=> HTCONDOR-2371 whole-node-memory

docs/v23/configuration/job-router-overview.md
I saw the references to "new syntax" when we highlight it as "ClassAd transforms" in the name of a section header above it. Then I saw a few other opportunities for minor improvements.
=> Various updates to CE ClassAd transform migration

config/01-ce-router-defaults.conf
The existing expression for RequestGPUs will always evaluate to Undefined outside of HTCondor matchmaking against a slot ad.
=> HTCONDOR-2501 Fix whole-node gpu routing to work with non-condor systems

config/05-ce-auth-defaults.conf, config/mapfiles.d/50-common-default.conf
Use the local UID_DOMAIN (users.htcondor.org) for the identity of 'condor' clients. Otherwise, in 23.9.x, the schedd won't recognize the job router as a queue superuser.
=> HTCONDOR-2549 daemon domain

config/01-ce-router-defaults.conf
BatchQueue is the first-class way to specify the queue in the batch system. We should use it instead of queue or remote_queue.
=> HTCONDOR-2563 batch-queue

src/condor_ce_host_network_check
The openssl formats DNs differently in EL7, EL8, and EL9. Request the old format explicitly so that we know how to parse it.
=> HTCONDOR-2637 Request old DN formatting for certificate issuer

config/01-ce-router-defaults.conf
Setting expressions for the routed job's resource requests doesn't work properly if the routed job is going through the grid universe.
=> HTCONDOR-2703 whole-node

config/01-ce-router-defaults.conf
Setting expressions for the routed job's resource requests doesn't work properly if the routed job is going through the grid universe.
=> HTCONDOR-2703 Use whole-node custom resource requests only for HTCondor

docs/v24/configuration/writing-job-routes.md
Verified locally using:
```
podman run --rm -it -v ${PWD}:/docs -p 8000:8000 docker.io/squidfunk/mkdocs-material:7.1.0
```
=> Fix spots where we still want code block tabs

contrib/bdii/htcondor-ce-provider, contrib/bosco/bosco-cluster-remote-hosts.py, src/collector_to_agis, src/condor_ce_host_network_check, src/condor_ce_info_status, src/condor_ce_jobmetrics, src/condor_ce_register, src/condor_ce_router_defaults, src/condor_ce_scitoken_exchange, src/condor_ce_trace, src/condor_ce_view, src/gratia_cleanup.py, src/htcondorce/info_query.py, src/htcondorce/tools.py, src/htcondorce/web.py, src/htcondorce/web_utils.py, src/verify_ce_config.py
condor_ce_trace required major changes due to altered or removed interfaces.
=> HTCONDOR-2688 python-htcondor2
