htcondor/htcondor-ce

CMakeLists.txt
config/htcondor-ce.spec
src/condor_ce_info_query.py
src/condor_ce_info_status

This should make reuse easier. Note that the PR is based on my master, which is one commit ahead (see PR #6).

Separate condor_ce_info_status into library and script

---

src/condor_ce_trace

https://jira.opensciencegrid.org/browse/SOFTWARE-1750

Sw1750 error handling improvements

---

src/condor_ce_run
src/condor_ce_trace

https://jira.opensciencegrid.org/browse/SOFTWARE-1787
Based on my master (#8). Not sure what the proper etiquette is here when submitting mutliple PR's that are working on the same sections of code...

Sw1787 dry run

---

src/condor_ce_run

Same issue as dee7e0501236a7fbf89afc23401b541f62d14cc3 except for condor_ce_run

Fix cleanup bug in condor_ce_run

---

src/condor_ce_info_query.py
src/condor_ce_info_status

This adds getSubmitFileAdditions(resource_ad) which returns a list of strings containing lines to be appended to a submit file.
There is also a --submitfile command-line option for condor_ce_info_status that prints out the submit file lines for the first resource that matches the given constraints.
A --name constraint (compares resource Name) was added to make that useful.

Add submit file generation (SOFTWARE-1760)

---

src/condor_ce_run
src/condor_ce_tools.py

https://jira.opensciencegrid.org/browse/SOFTWARE-1641

Sw1641 run attributes

---

src/condor_ce_run
src/condor_ce_tools.py
src/condor_ce_trace

fixed exception handling for extra attr file since the OptParse object
returns None for undefined attributes.

Fix generate_submit_files() editing the job_info dict in place. Also

---

src/condor_ce_trace

for the CE (SOFTWARE-1821). Also fixed indentation that pylint was
complaining about.
https://jira.opensciencegrid.org/browse/SOFTWARE-1821?filter=12359

Catch exceptions that result from failure to retrieve socket information

---

src/condor_ce_router_defaults

osg-job-environment.conf to the job's environment (SOFTWARE-1862)

Prevent passing of blank shell variables specified in

---

src/condor_ce_info_query.py
src/condor_ce_info_status

This allows filtering by an arbitrary classad expression against the
attributes in a ResourceAd.

Add --constrain option to condor_ce_info_status (SOFTWARE-1842)

---

src/condor-ce
src/condor_ce_run
src/condor_ce_trace

and extending the service wait time to avoid test failures in the nightlies

Improvements to error messages

---

src/condor_ce_env_bootstrap

instead of trying to source /etc/sysconfig/condor-ce

htcondor-ce-collector should source /etc/sysconfig/condor-ce-collector

---

.gitignore
.travis.yml
tests/test_inside_docker.sh

Add testing 

---

.travis.yml
tests/test_inside_docker.sh

Also, adding a test to install the resulting RPMs.  Still working on test results.

Adding el7 test in addition to the el6

---

.travis.yml

Correct Email settings for travis.yml

---

tests/test_inside_docker.sh

To fix the failing builds.  Oh at the failing builds!

Adding yum clean all to clear the yum cache before test

---

.travis.yml
tests/setup_tests.sh

Split out the test setup so we can start system services using systemd or regular init.

Split out test setup so we can start system services

---

src/condor_ce_trace

Fix condor_ce_trace having exit code when timing out

---

config/condor_mapfile

https://jira.opensciencegrid.org/browse/SOFTWARE-2433

Allow mapping of Terana eScience hostcerts

---

CMakeLists.txt
config/condor-ce-collector.conf
config/condor-ce-collector.service
config/condor-ce.conf
config/condor-ce.service
config/htcondor-ce.spec
src/condor-ce
src/condor-ce-collector
src/condor_ce_startup
tests/test_inside_docker.sh

- EL7 tmpfs support
- Run against `osg-test` trunk for tests that accommodate this PR

Remove the HTCondor-CE init script on EL7 (SOFTWARE-2419)

---

src/condor-ce
src/condor_ce_startup

[SOFTWARE-1856](https://jira.opensciencegrid.org/browse/SOFTWARE-1856)
@bbockelm: Feel free to look over these changes, too!

HTCondor-CE should detect and refuse to start with invalid config

---

config/htcondor-ce.spec
tests/test_inside_docker.sh

Fix rpm cleanup on EL7

---

config/htcondor-ce.spec
src/condor_ce_view

Background: https://jira.opensciencegrid.org/browse/SOFTWARE-2477
Also some spec file updates. I tested the option handling and verified that the CE View page now works upon service restart.

Handle '-local-name' option in the CE View

---

src/condor_ce_view

the port to bind to instead of the pool to track to respect DaemonCore.

Accept all DaemonCore options (SOFTWARE-2481). Change '-p' to refer to

---

src/htcondorce/web_utils.py

Starting pull request, do not merge until get the go ahead from Atlas in [Software-2591](https://jira.opensciencegrid.org/browse/SOFTWARE-2591)

Adding resource entry lines to agis json. (SOFTWARE-2591)

---

src/bdii/condor_ce_bdii_generate_glue2.py

1. Remove unnecessary ".ch".
2. Remove disallowed "GLUE2COmputingShareMax*" on ResourceID.
3.  Add replace function to remove double quote.

Fix bugs to pass GLUE2 Validator.

---

src/verify_ce_config.py

Only complain about not being osg-configured if osg-configure is present

---

config/htcondor-ce.spec
src/verify_ce_config.py

And bump the version number/changelog in the spec

Merge changes from 'master'

---

config/htcondor-ce.spec
tests/setup_tests.sh

and package the missing `ceview/metrics` directory

Fix EL6 Travis-CI tests (v2)

---

config/htcondor-ce.spec
tests/setup_tests.sh

and package the missing `ceview/metrics` directory

Fix EL6 Travis-CI tests (master)

---

src/verify_ce_config.py

https://jira.opensciencegrid.org/browse/SOFTWARE-2814

Fix traceback if JOB_ROUTER_ENTRIES not present (SOFTWARE-2814)

---

src/verify_ce_config.py

Fix traceback if JOB_ROUTER_ENTRIES not present (SOFTWARE-2814) (v2)

---

src/condor_ce_metric

For merging into the V2 branch for OSG 3.3

Import the right lib, get_spooldir() got moved to web_utils (V2)

---

src/condor_ce_trace

https://jira.opensciencegrid.org/browse/SOFTWARE-3030

condor_ce_trace: use python bindings for condor_ping (SOFTWARE-3030)

---

config/htcondor-ce.spec

https://jira.opensciencegrid.org/browse/SOFTWARE-3050

Remove EL5-isms

---

src/bdii/htcondor-ce-provider

The previous previous pull request did not work as anticipated. The renaming was done but the old code was used.

Improvded GLUE2 information provider

---

src/condor_ce_startup
src/verify_ce_config.py

It's nicer to have all the verification stuff in a single script

Verify QUEUE_SUPER_USER_MAY_IMPERSONATE via python bindings

---

config/condor_mapfile.osg
contrib/puppet/osg_ce_condor/files/condor_mapfile

This PR adds mapping for InCommon certs and updates the sample puppet module for condor-ce

Add InCommon mapping to condor_mapfile

---

config/01-common-collector-defaults.conf
config/condor_mapfile
rpm/htcondor-ce.spec

Bump version to 3.1.1

---

rpm/htcondor-ce.spec

The BDII package needs files...

Remove missed uw build/BDII conditionals

---

contrib/bdii/htcondor-ce-provider

This is the total number of physical CPUs (one physical CPU per socket) and is not the same as number of cores.

Remove PhysicalCPUs

---

contrib/bdii/htcondor-ce-provider

Dynamically generate execution environments from host specifications.

Added Multiple Execution Enviroments

---

contrib/bdii/htcondor-ce-provider

Some improvements from running in production
- Adding a timeout on CE queries
- Adding a try/catch

production hardening

---

config/01-ce-auth-defaults.conf
config/01-ce-auth-defaults.conf.osg
config/01-ce-auth.conf
config/01-ce-auth.conf.osg
tests/test_inside_docker.sh

This is the default value in < HTCondor 8.9.0.

Explicitly set ALLOW_READ to support HTCondor 8.9.0 (SOFTWARE-3538)

---

CMakeLists.txt
rpm/htcondor-ce.spec

I'm liking this new version branch PR method

Bump version to 3.2.1

---

src/condor_ce_store_cred

http://research.cs.wisc.edu/htcondor/manual/v8.8/Security.html#x36-2780003.8.3

Add tool for storing PASSWORD auth credentials

---

rpm/htcondor-ce.spec

@timtheisen this reminds me that if we ever get that blahp unification done, the HTCondor packaging should probably build the blahp

Make blahp requirement binary package specific (SOFTWARE-3623)

---

config/02-ce-condor-defaults.conf
config/02-ce-condor.conf
config/02-ce-lsf-defaults.conf
config/02-ce-lsf.conf
config/02-ce-pbs-defaults.conf
config/02-ce-pbs.conf
config/02-ce-sge-defaults.conf
config/02-ce-sge.conf
config/02-ce-slurm-defaults.conf
config/02-ce-slurm.conf
src/condor_ce_router_defaults

https://opensciencegrid.atlassian.net/browse/SOFTWARE-3639

Update job router configuration to use new HTCondor multi-line syntax (SOFTWARE-3637)

---

config/05-ce-view-defaults.conf

https://opensciencegrid.atlassian.net/browse/SOFTWARE-3668

 Update the central collector via TCP (SOFTWARE-3668) 

---

contrib/apelscripts/condor_ce_blah.sh

Inspired by 5070b8bf74581ea8b92c3ee458840302679d4945

Update condor_ce_blah to propagate failures properly

---

CMakeLists.txt
contrib/apelscripts/README.md
contrib/apelscripts/condor_batch.sh
contrib/apelscripts/condor_blah.sh
rpm/htcondor-ce.spec

[new_blah_script.pdf](https://github.com/htcondor/htcondor-ce/files/3407018/new_blah_script.pdf)

 Replace CE query to Batch system query, to get data on Removed jobs 

---

.travis.yml
tests/setup_tests.sh

I think this is how `deploy` is intended to be used. See this relevant build: https://travis-ci.org/brianhlin/htcondor-ce/jobs/566626525#L7209-L7210

Deploy immediately after tests for tags in htcondor/htcondor-ce

---

tests/README.scitokens.md

https://github.com/htcondor/htcondor-ce/blob/master/config/01-ce-auth-defaults.conf#L22

Fix mapping example

---

CMakeLists.txt
rpm/htcondor-ce.spec
src/verify_ce_config.py

Fix undefined errexit

---

contrib/bdii/htcondor-ce-provider

Added IOError exception handling, generated when querying the CE Collector

Added IOError exception handling

---

contrib/bdii/htcondor-ce-provider

Co-Authored-By: Matyas Selmeci <matyas@cs.wisc.edu>

Apply suggestions from code review

---

contrib/bdii/htcondor-ce-provider

V3 external BDII fixes

---

.travis.yml
CMakeLists.txt
README.md
config/01-ce-info-services-defaults.conf
config/condor-ce-collector-config.service
config/condor-ce-collector-config.timer
config/condor-ce-collector.service
config/condor-ce.service
config/condor_config
rpm/htcondor-ce.spec
tests/setup_tests.sh

First part of the series in #251

V3 packaging updates

---

docs/releases.md

Just copied what was in https://github.com/htcondor/htcondor-ce/releases/

Add HTCondor-CE 3 version history

---

src/verify_ce_config.py

Grabbing formatting updates from #267

Unify verify ce config

---

docs/releases.md

@timtheisen I believe this is what you wanted from me for the HTCondor-CE 4 announcement. The [homepage](https://htcondor-ce.readthedocs.io/en/latest/) should give you a good starting point for an intro blurb to introduce people to HTCondor-CE

Add version 4 changelog

---

src/verify_ce_config.py

Backport undefined errexit

---

CMakeLists.txt
rpm/htcondor-ce.spec

Packaging + tagging first. I'll submit doc updates in another PR

Bump version to 4.1.0

---

CMakeLists.txt
rpm/htcondor-ce.spec

Similarly packaging + tagging first; doc updates to come

Bump version to 3.4.0

---

docs/batch-system-integration.md

http://condor-wiki.cs.wisc.edu/index.cgi/tktview?tn=7284

Document job route order bug (#7284)

---

docs/batch-system-integration.md
docs/css/superfences.css
docs/releases.md
mkdocs.yml

Ready to be merged with the CHTC release of 3.4.0

3.4.0 documentation (SOFTWARE-3862)

---

config/01-ce-router-defaults.conf.in

CurrentTime is set to time() in every ClassAd but may be overridden

time() is preferred over CurrentTime

---

docs/batch-system-integration.md

If this look ok, I'll make another PR for master

Add options for specifying job route order in new versions of HTCondor (stable)

---

contrib/bdii/htcondor-ce-provider

Glue validation fixes (stable)

---

contrib/bdii/htcondor-ce-provider

Co-Authored-By: Matyas Selmeci <matyas@cs.wisc.edu>

Minor fixups from code review (master)

---

contrib/bdii/99-ce-bdii.conf
contrib/bdii/htcondor-ce-provider

Cherry-picked changes from #311

Adding Benchmark parameters (stable)

---

src/verify_ce_config.py
tests/test_verify_ce_config.py

Changes from #318 cherry-picked to `master`. Closes #233 (and maybe this time it'll actually get closed?)

Identify misconfigured routes and fix bad ClassAd detection for master (SOFTWARE-3896, SOFTWARE-4052)

---

contrib/bdii/99-ce-bdii.conf
contrib/bdii/htcondor-ce-provider
docs/installation/htcondor-ce.md

Addresses issues raised in #320

Various BDII provider fixups

---

contrib/bdii/99-ce-bdii.conf
contrib/bdii/htcondor-ce-provider
docs/installation/htcondor-ce.md

Cherry-picked from #321. Closes #320

Various BDII provider fixups (master)

---

config/01-ce-router-defaults.conf.in

Remove the "(JobStatus == 5 && isUndefined(RoutedToJobId))" remove
reason clause since that should already be specified by the hold
reason in those cases.

Refactor SYSTEM_PERIODIC expressions and reasons

---

templates/index.html

Part of #329 -- the CI doesn't pass on that one so I'm trying to figure out which part of it is broken.

Fix whitespace in index.html

---

docs/installation/htcondor-ce.md
docs/releases.md
docs/verification.md
rpm/htcondor-ce.spec

This PR can go with the next release

Add documentation for APEL uploader services (#323)

---

docs/index.md
docs/overview.md

And update phrasing on the homepage to reflect language in the HTCondor-CE Translational CS paper

Add HTCondor-CE Intro video

---

CMakeLists.txt
contrib/bdii/htcondor-ce-provider
rpm/htcondor-ce.spec

Fix a stacktrace that occurs when HTCONDORCE_SPEC isn't defined (stable)

---

config/05-ce-collector-auth.conf

condor_mapfile.central_collector is in /etc/condor-ce

Update central collector condor_mapfile path

---

src/htcondorce/rrd.py
src/htcondorce/web.py
templates/index.html

- Request both schedds and tableattribs at the same time, waiting until both requests are complete
- Fix the HTML tag nesting for the table

Various CEView polishing: Info table, RRD generation, ClassAd to JSON

---

src/htcondorce/web.py

Address the issues from PR #355 with serializing HTCondor `Undefined`.
Unfortunately, `classad.Value.Undefined` is of type `int`, and `json.dumps()` converts it to "2". (The custom `JSONEncoder` class is only called for unknown types.) Instead use HTCondor JSON conversion, then back to a Python object.
The round-trip through JSON isn't great, but we want to concatenate multiple ClassAd objects into a single JSON object. This should avoid unexpected surprises that may arise from treating JSON as raw strings.

CEView: Handle classad.Value.Undefined in ClassAd to JSON

---

overwrite_theme/main.html

Add site-wide office hours admonition

---

contrib/bdii/htcondor-ce-provider

Add support for comma-separated central managers (BDII)

---

src/condor_ce_info_status

Python 3 compat for condor_ce_info_status

---

src/condor_ce_host_network_check

discovered randomly while debugging #381

add missing print >> redirect

---

src/condor_ce_jobmetrics

The first block of commits are cleanup and could probably stand alone.
There is still plumbing work to be done for the collected gpu info.

collect stats for gpu jobs (SOFTWARE-4183)

---

rpm/htcondor-ce.spec

Drop htcondor-ce requirement from htcondor-ce-bdii 

---

contrib/bdii/htcondor-ce-provider

Will make it easier to address issues in #364. I tested this against our local cluster and things look with a quick diff (number of lines is the same but there are some differences that look simply like slight changes in LDIF entry ordering).
@aleita @kreczko @andiri @lfield would you guys be able to verify output of the refactored provider in this PR? For now, I'm going to move forward on providing multi collector support assuming that this PR is acceptable!

Refactor the BDII provider

---

docs/installation/htcondor-ce.md

Add notes to clarify APEL/BDII support

---

rpm/htcondor-ce.spec
tests/test_inside_docker.sh

https://opensciencegrid.atlassian.net/browse/HTCONDOR-84
Bonus removal of unnecessary `grid-certificates` OSG package requirement

Fix CHTC repo non-HTCondor package installs (HTCONDOR-84)

---

config/05-ce-view-defaults.conf

Remove circular definition that caused condor_gangliad to thrash (stable)

---

src/condor_ce_jobmetrics
src/condor_ce_metric
src/condor_ce_view
src/htcondorce/rrd.py
src/htcondorce/web.py
src/htcondorce/web_utils.py
templates/pilots.html
templates/view_base.html
templates/vos.html
tests/test_inside_docker.sh

- The usual byte-string stuff
- Who knew that `Dict().keys()` now returns a `dict_keys` "view" object?

Various CE View fixes (HTCONDOR-13)

---

src/condor_ce_info_status

clashing with future print/python3

python2 print remnant

---

.github/workflows/upload_rpms.yaml
tests/build_rpms.sh
tests/sftp_upload.sh

Finally got it working on my personal repo

Re-enable CI build transfer on new tag

---

rpm/README.release.md
rpm/htcondor-ce.spec

I wrote it down since I managed to mess it up twice and I'm the one that wrote the CI!

Release process documentation

---

src/verify_ce_config.py

Let's see if I did this right...

Merge JR entry name check from V4-branch (HTCONDOR-406)

---

docs/v5/releases.md

This captures the tickets and other PRs that are making it into 5.1.0: https://opensciencegrid.atlassian.net/issues/?jql=project%20%3D%20%22HTCONDOR%22%20AND%20fixVersion%20%3D%20%225.1.0%22

V5.1.0 update release notes

---

docs/v5/configuration/job-router-overview.md
docs/v5/configuration/writing-job-routes.md
docs/v5/remote-job-submission.md
docs/v5/troubleshooting/common-issues.md
docs/v5/troubleshooting/debugging-tools.md
docs/v5/troubleshooting/logs.md
docs/v5/troubleshooting/remote-troubleshooting.md
docs/v5/verification.md
mkdocs.yml

ToddT gave the go ahead to merge docs immediately with review after the fact

Split up troubleshooting doc

---

CMakeLists.txt
rpm/htcondor-ce.spec

As discussed, we'll just tag this so that OSG can build it for their 3.5 release series

Bump version to 4.5.2

---

config/condor-ce-collector.conf
config/condor-ce.conf

https://opensciencegrid.atlassian.net/browse/HTCONDOR-512

Change /var/lock/condor-ce/user to be 1777 to match the spec file

---

tests/containers/entrypoint/10-ce.conf
tests/containers/entrypoint/Dockerfile

The EL8 was pretty mad without powertools and make

Add necessary bits for EL8 dev image build

---

.github/workflows/python-linters.yaml
contrib/bosco/bosco-cluster-remote-hosts.py

Draft PR for https://opensciencegrid.atlassian.net/browse/SOFTWARE-4687

 HTCondor-CE pylint GHA: replace hardcoded python file list (SOFTWARE-4687)

---

.github/workflows/build_and_test_rpms.yml
README.md

This results in tests being kicked off for forks, making dev a little easier

Test on push; fix status badge

---

docs/v5/configuration/job-router-overview.md
docs/v5/configuration/writing-job-routes.md
docs/v5/releases.md

I think I got everything in the right places here. Please have a look and let me know.

Added warning to CE documentation for HTCONDOR-622 (HTCONDOR-712)

---

docs/v5/operation.md

Add docs for checking authentication method and identity of job submitters.

HTCONDOR-897 Docs for client auth in AuditLog

---

config/condor_config

I just went with the simple fix.

HTCONDOR-1106: Ensure that the correct port is used

---

config/01-ce-auth-defaults.conf

Remove ssl config params that match default values.

HTCONDOR-1345 ssl-cert-config

---

.github/workflows/build_and_test_rpms.yml
.github/workflows/python-linters.yaml
.github/workflows/upload_rpms.yaml

Roll back GitHut actions OS image to Ubuntu 20.04.

HTCONDOR-1553 fix GitHub tests

---

docs/v5/configuration/htcondor-routes.md

HTCONDOR-1013 Add example of using AuthTokenSubject 

---

.github/workflows/build_and_test_rpms.yml
.github/workflows/upload_rpms.yaml

Updates deprecated node.js 12 actions to node.js 16.

Fix GHA deprecation warnings (SOFTWARE-5354)

---

docs/v23/configuration/writing-job-routes.md

This doc (and probably the common issues doc) will need major updates for HTCondor-CE 24

Update HTCondor-CE version reference

---

docs/v23/configuration/job-router-overview.md
docs/v23/configuration/writing-job-routes.md
docs/v6/configuration/job-router-overview.md
docs/v6/configuration/writing-job-routes.md

There is only one ticket for this release. So including doc typos in that ticket.

HTCONDOR-2501: Fixup POST_ROUTE docs

---

contrib/bdii/htcondor-ce-provider

The xquery function is deprecated.

Replace outdated xquery command
